FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME gha-demo1
ENV MONGODB_CLUSTER_ADDRESS cluster0.hj2t9lx.mongodb.net
ENV MONGODB_USERNAME gdnght1992
ENV MONGODB_PASSWORD PSBDdxqB2E5RYTz1

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]